server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
#endpoints:
#  shutdown:
#    enabled: true
#    sensitive: false

#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin123
  